name: Build and Publish Docker
on: [push]
jobs:
    build:
        run-on: ubuntu-latest
        steps:
        - uses: actions/checkout@master
        - name: Publish to Docker Repository
          uses: MarcW1g/actions-docker-cicd-demo
          with:
            name: marcwiggerman/actions-docker-cicd-demo
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}